play/urls.py
from django.urls import path
from . import views

app_name = 'play'

urlpatterns = [
    path('round/', views.play_round, name='round'),
    path('after/', views.play_round_after, name='after'),
    path('delete/<int:quiz_id>', views.delete, name='delete'),
    path('result/', views.play_result, name='result'),
    path('prev/<int:user_id>', views.prev_page_redirect, name='prev'),
]

room/urls.py
from django.urls import path, include
from . import views

app_name = 'room'

urlpatterns = [
    path('', views.index, name="assets"),
    path('create_room/', views.create_room, name='create'),
    path('<int:room_id>/', views.room, name='asset'),
    path('<int:room_id>/quizs/', include('quiz.urls')),
    path('<int:room_id>/plays/', include('play.urls')),
]

room/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from common.models import User

class Room(models.Model):
    name = models.CharField(max_length=20)

    play_round = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    limit_time = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(30)])
    host = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='host_test')
    users = models.ManyToManyField(User, related_name='users_test_name')
    is_start = models.IntegerField(default=0)
    play_user_count = models.IntegerField(default=0)

    def __str__(self):
        return self.name

room/forms.py
from django import forms
from .models import Room


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('name', 'play_round', 'limit_time')
        labels = {
            'name': '방제목',
            'play_round': '라운드',
            'limit_time': '제한시간',
        }

room/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from quiz.models import Quiz
from .forms import RoomForm
from .models import Room
from common.models import User

logger = logging.getLogger(__name__)


def index(request):
    if not request.user.is_authenticated:
        return redirect('signup')

    user = User.objects.get(id=request.user.id)
    user.ready = 0
    user.save()

    room_all = Room.objects.all()
    for room_data in room_all:
        if user in room_data.users.all():
            room_data.users.remove(user)
        if user.id == room_data.host_id:
            if not room_data.users.exists():
                room_data.delete()
            else:
                room_data.host_id = None
                room_data.host_id = room_data.users.all().order_by('?').first()
                room_data.save()

    room_list = Room.objects.all()
    context = {'room_list': room_list}
    return render(request, 'room/room_list.html', context)


@login_required(login_url='/')
def create_room(request):
    if not request.user.is_authenticated:
        return redirect('signup')
    logger.debug(request.user)
    if request.method == "POST":
        form = RoomForm(request.POST)
        # logger.debug()
        if form.is_valid():
            room = form.save(commit=False)
            room.host = request.user
            room.save()
            return redirect('room:asset', room_id=room.id)
    else:
        form = RoomForm()
    return render(request, 'room/create_room.html', {'form': form,
                                                     'number': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})


@login_required(login_url='/')
def room(request, room_id):
    if not request.user.is_authenticated:
        return redirect('signup')

    room = get_object_or_404(Room, pk=room_id)
    print(f'room type : {room, type(room), room.id}')
    room_all = Room.objects.all()
    user = User.objects.get(id=request.user.id)
    for room_data in room_all:
        if user in room_data.users.all() and user not in room.users.all():
            return redirect('room:assets')

    if room.is_start == 1:
        return redirect('room:assets')

    player = str(request.user)

    room.users.add(request.user)
    room.save()

    # 임의적으로 user 의 score 를 0 으로 변환하는 코드
    user = request.user
    user.score = 0
    user.refresh_check = 0
    user.save()

    quiz_count = Quiz.objects.filter(room_id=room_id, user_id=request.user)

    context = {'room': room,
               'room_round': room.play_round,
               'quiz_count': quiz_count.count(),
               'username': player}
    return render(request, 'room/in_room.html', context)

templates/room/create_room.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/create_room.css' %}?after">
    <div class="container">
        <form method="post" class="post-form my-3" enctype="multipart/form-data">
            <h3 class="my-3 border-bottom pb-2" style="font-weight: 500;">방 생성</h3>
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="form-group mb-4">
                <label for="name">방제목</label>
                <input type="text" class="form-control" name="name" id="name"
                       value="{{ form.name.value|default_if_none:'' }}">
                <div id="emailHelp" class="form-text">방 제목은 20글자 이내입니다.</div>
            </div>
            <div class="form-group mb-4">
                <label for="play_round">라운드</label>
                <select name="play_round" id="play_round" class="form-select"
                        value="{{ form.play_round.value|default_if_none:'' }}">
                    {% for i in number %}
                        <option>{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group mb-4">
                <label for="limit_time">제한시간</label>
                <input type="text" class="form-control" name="limit_time" id="limit_time"
                       value="{{ form.limit_time.value|default_if_none:'' }}">
                <div id="emailHelp" class="form-text">제한시간은 최대 30초 입니다.</div>
            </div>
            <div class="container-btns">
                <a id="chat-close-btn" class="btn btn-danger" href="{% url 'room:assets' %}">이전으로</a></button>
                <button type="submit" style="float:right;" class="btn btn-primary">방생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/room/in_room.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/in_room.css' %}?after">
    <div class="container">
        <div class="RoomSettingsContainer">
            <div class="flex-item">방제목 : {{ room.name }}</div>
            <div class="flex-item">라운드 : {{ room.play_round }}</div>
            <div class="flex-item">라운드 당 제한 시간 : {{ room.limit_time }}</div>
        </div>

        {% if user.is_authenticated %}
            {% csrf_token %}
            <div class="widget">
                <div class="mb-3 text-center">
                    <h4>
                        <span>이용자 리스트</span>
                    </h4>
                </div>
                <table class="table small mb-5">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">유저</th>
                        <th scope="col">준비</th>
                    </tr>
                    </thead>
                    <tbody id="user_list"></tbody>
                </table>
                <div class="gap-0"></div>
            </div>
        {% endif %}

        <div class="chatMessageContainer"> <!--css-->
            <p style="border-bottom: 1px solid rgb(173, 173, 173); margin-bottom:0px;">&nbsp;채팅창</p>
            <textarea id="chat-log" disabled></textarea>
        </div>
        <form id="post-form">
            {% csrf_token %}
            <input type="hidden" name="username" id="username" value="{{ username }}"/>
            <input type="hidden" name="room_id" id="room_id" value="{{ room.id }}"/>
        </form>
        <div class="chatsendContainer">
            <input id="chat-message-input" type="text" size="50px">
            <input class="mt-3" id="chat-message-submit" type="button" value="보내기">
            <input id="ready" type="button" style="float:right; margin-top: 15px;" value="ready" hidden>
        </div>

        <button id="chat-close"
                style="border:none;background-color: crimson;margin-top: 10px;height: 35px;border-radius: 5px;"><a
                id="chat-close-btn"
                href="{% url 'room:assets' %}">나가기</a>
        </button>
        <a class="btn btn-success disabled" style="float:right;margin-top: 10px;margin-left: 10px;height: 35px;"
           id="start-button"
           href="{% url 'room:play:round' room.id %}" hidden>start
        </a>
        <a id="create-button" style="float:right;margin-top: 10px;height: 35px;"
           href="{% url 'room:quiz:create' room.id %}" hidden
                {% if room_round == quiz_count %}
           class="btn btn-info disabled"
                {% else %}
           class="btn btn-info"
                {% endif %}>
            퀴즈 생성
        </a>
    </div>

    <div>
        <hidden id="room-name" value="{{ room.id }}" user="{{ user.username }}" host="{{ room.host }}"></hidden>
    </div>

    <style>
        #chat-close-btn {
            text-decoration: none;
            color: black;
        }
    </style>
{% endblock %}
{% block script %}
    <script src="{% static 'js/in_room.js' %}"></script>
{% endblock script %}

templates/room/room_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/room_list.css' %}?after">
    <div class="RoomListContainer">
        <div class="RoomsContainer">
            <div class="ShowRoomIdentify">
                <b>방 제목</b>
                <b>호스트</b>
                <b>라운드</b><br>
            </div>
            {% if user.is_authenticated %}
                {% csrf_token %}
                {% if room_list %}
                    {% for room in room_list %}
                        <pr>
                            {% if room.is_start == 0 %}
                                <a class="btn" href="{% url 'room:asset' room.id %}">
                                    <text>방제 : {{ room.name }}</text>
                                    <text>호스트 : {{ room.host }}</text>
                                    <text>라운드 : {{ room.play_round }}</text>
                                </a>
                            {% endif %}
                        </pr>
                    {% endfor %}
                {% else %}
                    <h1 class="text-center my_title">방이 없습니다.</h1><br>
                {% endif %}
                </div>
                <div class="MakeRoomOrLogoutContainer"><!--css-->
                    <a class="btn btn-primary" href="{% url 'room:create' %}"><br><br>방 생성</a>
                    <a class="btn btn-primary" style="background-color: crimson;" href="{% url 'logout' %}"><br><br>로그아웃
                    </a>
                    <button type="button" onClick="window.location.reload();">새로 고침</button>
                </div>
            {% endif %}
    </div>
{% endblock %}